### ISSUE TITLE
Update datamodel/seedData.js with appropriate seed data 

### ISSUE THREAD

**Issue by philipmjohnson** [agilegardenclub/public-garden-45ght3cf#1]
Please do work for this task in a branch named issue-001.

The seed database file is filled with data about random seeds. This file should be updated to reflect data that:

1. Accurately reflects seed data relevant to Bellingham.
2. Includes seeds actually used in Jenna's garden. 

This process may reveal the need for additional fields regarding seeds, which is great.

**Comment by Jennacd** [comment]
Is this table sufficient? https://docs.google.com/spreadsheets/d/1Sv91XNbB50Y4dNnBlh_uWHZ7kEvj-QlarNPt1OFjJq0/edit#gid=2077950265
